"use client";

import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/common/Sidebar";
import Header from "@/components/common/Header"
import { useState, useEffect } from "react"
import { fetchFromLocalStorage, removeFromLocalStorage, storeInLocalStorage } from '@/utils/LocalStorage';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({
  children,
}: LayoutProps) {
  const [token, setToken] = useState(null as string | null);

  useEffect(() => {
    setToken(fetchFromLocalStorage('AccessToken') as string)
  }, [token])

  return (
    <html lang="en">
      <body
        className={`project ${geistSans.variable} ${geistMono.variable} antialiased`}
      > 

      <Header token={token} setToken={setToken} />
      <Sidebar token={token} />
      {children}

      </body>
    </html>
  );
}
