name: Deploy Project

on:
  push:
    branches:
      - main
    path:
      - 'frontend/**'
      - 'nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build frontend docker image
        run: |
          docker build -t frontend:latest ./frontend/.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag frontend:latest strawhatshanks/frontend:latest
          docker push strawhatshanks/frontend:latest
      
      - name: Push nginx docker image
        run: |
          docker build -t nginx:latest ./nginx/.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag nginx:latest strawhatshanks/nginx:latest
          docker push strawhatshanks/nginx:latest
      
      - name: Build auth backend docker image
        run: |
          docker build -t auth-backend:latest ./user-auth/.
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag auth-backend:latest strawhatshanks/auth-backend:latest
          docker push strawhatshanks/auth-backend:latest
      
  deploy:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and Deploy
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem
          ssh -o StrictHostKeyChecking=accept-new -i ec2-key.pem ubuntu@${{ secrets.EC2_IP }} << 'EOF'

            # Create the .env file and write secrets to it
            mkdir -p /home/ubuntu/user-auth
            cd /home/ubuntu/user-auth
            touch .env

            echo "NGINX_PORT=${{ secrets.NGINX_PORT }}" >> .env
            echo "AUTH_BACKEND_PORT_2=${{ secrets.AUTH_BACKEND_PORT_2 }}" >> .env
            echo "AUTH_BACKEND_PORT_1=${{ secrets.AUTH_BACKEND_PORT_1 }}" >> .env
            echo "MAIN_URL=${{ secrets.MAIN_URL }}" >> .env

            sudo docker pull strawhatshanks/frontend:latest
            sudo docker pull strawhatshanks/nginx:latest
            sudo docker pull strawhatshanks/auth-backend:latest

            # Navigate to the project directory
            # cd /home/ubuntu/user-auth 
            # touch /home/ubuntu/user-auth/.env
            
            sudo docker-compose --env-file .env down
            sudo docker-compose --env-file .env up -d --build
          EOF
